site_name: AuroraStack
site_author: Choonho Son
site_description: Python-based Open Source MSA Framework for Developing gRPC & Rest Server in Kubernetes
repo_name: aurorastack-core
repo_url: https://github.com/aurorastack/aurorastack-core/
site_url: https://aurorastack.io
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 AuroraStack

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: joaomdmoura
      repo: crewAI
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/light-bulb-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    # - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.share

nav:
  - Home: '/'
  - Core Concepts:
    - Framework: 'core-concepts/Framework.md'
    - Interface: 'core-concepts/Interface.md'
    - Service: 'core-concepts/Service.md'
  - How to Guides:
    - Getting Started: 'how-to/Getting-Started.md'
    - Design gRPC API Spec: 'how-to/API-Spec.md'
    - Developing Server Code 'how-to/Server-Code.md'
    - Launching Server: 'how-to/Run-Server.md'
    - Testing Server: 'how-to/Test-Server.md'
  - Examples:
    - HelloWorld Server: https://github.com/aurorastack/helloworld"

extra_css:
  - stylesheets/output.css
  - stylesheets/extra.css

#plugins:
#  - material/social

extra:
  analytics:
    provider: google
    property: G-TV6R44L088
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/ncgqX6CS3V
    - icon: fontawesome/brands/github
      link: https://github.com/aurorastack/
